
GET http://localhost:3100/api/rgb

###


PUT http://localhost:3100/api/rgb
Content-Type: application/json

{
  "r": 255,
  "g": 0,
  "b": 0
}

###


PUT http://localhost:3100/api/rgb
Content-Type: application/json

{
  "r": 0,
  "g": 0,
  "b": 255
}
###

